<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="base">

<link name="world"></link>
<joint name="world_to_base" type="fixed">
    <origin xyz="0 0 ${upper_length + lower_length + 4*end_effector_depth}" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="base"/>
</joint>

<link name="base">
<visual>
    <geometry>
        <cylinder
            length="${base_depth}"
            radius="${base_radius}"
        />
    </geometry>
    <material name="base"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${base_depth}"
            radius="${base_radius}"
        />
    </geometry>
</collision>
</link>

</robot>
