<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">

<link name="ee">
<visual>
    <geometry>
        <cylinder
            length="${ee_depth}"
            radius="${ee_radius}"
        />
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <material name="ee"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${ee_depth}"
            radius="${ee_radius}"
        />
    </geometry>
    <origin rpy="0 0 0" xyz="0 0 0"/>
</collision>

<visual>
    <geometry>
        <cylinder length="${lower_width}" radius="${ee_depth/2}" />
    </geometry>
    <origin xyz="${ee_radius} 0 0" rpy="0 ${pi/2} ${pi/2}" />
    <material name="ee"/>
</visual>
<collision>
    <geometry>
        <cylinder length="${lower_width}" radius="${ee_depth/2}" />
    </geometry>
    <origin xyz="${ee_radius} 0 0" rpy="0 ${pi/2} ${pi/2}" />
</collision>

<visual>
    <geometry>
        <cylinder length="${lower_width}" radius="${ee_depth/2}" />
    </geometry>
    <origin xyz="${cos(pi*2/3)*ee_radius} ${sin(pi*2/3)*ee_radius} 0" rpy="0 ${pi/2} ${pi*7/6}" />
    <material name="ee"/>
</visual>
<collision>
    <geometry>
        <cylinder length="${lower_width}" radius="${ee_depth/2}" />
    </geometry>
    <origin xyz="${cos(pi*2/3)*ee_radius} ${sin(pi*2/3)*ee_radius} 0" rpy="0 ${pi/2} ${pi*7/6}" />
</collision>

<visual>
    <geometry>
        <cylinder length="${lower_width}" radius="${ee_depth/2}" />
    </geometry>
    <origin xyz="${cos(pi*4/3)*ee_radius} ${sin(pi*4/3)*ee_radius} 0" rpy="0 ${pi/2} ${pi*11/6}" />
    <material name="ee"/>
</visual>
<collision>
    <geometry>
        <cylinder length="${lower_width}" radius="${ee_depth/2}" />
    </geometry>
    <origin xyz="${cos(pi*4/3)*ee_radius} ${sin(pi*4/3)*ee_radius} 0" rpy="0 ${pi/2} ${pi*11/6}" />
</collision>

</link>

<link name="gripper_base">
<visual>
    <geometry>
        <box size="0.03 0.05 0.05"/>
    </geometry>
    <origin xyz="0 0 -0.025" rpy="0 0 0"/>
</visual>
<collision>
    <geometry>
        <box size="0.05 0.03 0.05"/>
    </geometry>
    <origin xyz="0 0 -0.025" rpy="0 0 0"/>
</collision>
</link>

<link name="gripper_left">
<visual>
    <geometry>
        <box size="0.03 0.005 0.05"/>
    </geometry>
    <origin xyz="0 0 -0.025"/>
</visual>
<collision>
    <geometry>
        <box size="0.03 0.005 0.05"/>
    </geometry>
    <origin xyz="0 0 -0.025"/>
</collision>
</link>

<link name="gripper_right">
<visual>
    <geometry>
        <box size="0.03 0.005 0.05"/>
    </geometry>
    <origin xyz="0 0 -0.025"/>
</visual>
<collision>
    <geometry>
        <box size="0.03 0.005 0.05"/>
    </geometry>
    <origin xyz="0 0 -0.025"/>
</collision>
</link>

</robot>
