<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_parameters">

<xacro:macro name="link_upper" params="number">
<link name="upper_${number}">
<visual>
    <geometry>
        <cylinder
            length="${upper_length}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length/2} 0 0"
        rpy="0 ${pi/2} 0"
    />
    <material name="upper"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${upper_length}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length/2} 0 0"
        rpy="0 ${pi/2} 0"
    />
</collision>

<visual>
    <geometry>
        <cylinder
            length="${lower_width}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length} 0 0"
        rpy="${pi/2} 0 0"
    />
    <material name="upper"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${lower_width}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length} 0 0"
        rpy="${pi/2} 0 0"
    />
</collision>
</link>
</xacro:macro>

<xacro:link_upper number="1"/>
<xacro:link_upper number="2"/>
<xacro:link_upper number="3"/>

</robot>
