<?xml version="1.0"?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" name="base">

<xacro:macro name="stand_part" params="number yaw">

<visual name="stand_leg_${number}_visual_1">
    <pose>
        ${stand_radius*cos(yaw)}
        ${stand_radius*sin(yaw)}
        ${-stand_height/2}
        0 0 ${yaw}
    </pose>
    <geometry><box><size>
        ${stand_leg_depth} ${stand_leg_width} ${stand_height}
    </size></box></geometry>
</visual>
<collision name="stand_leg_${number}_collision_1">
    <pose>
        ${stand_radius*cos(yaw)}
        ${stand_radius*sin(yaw)}
        ${-stand_height/2}
        0 0 ${yaw}
    </pose>
    <geometry><box><size>
        ${stand_leg_depth} ${stand_leg_depth} ${-stand_height}
    </size></box></geometry>
</collision>
<inertial>
    <pose>
        ${stand_radius*cos(yaw)} ${stand_radius*sin(yaw)} ${-stand_height/2}
        0 0 {yaw}
    </pose>
    <mass>${stand_vertical_mass}</mass>
    <xacro:box_inertia_sdf
        mass="${stand_vertical_mass}"
        w="${stand_leg_depth}" h="${stand_leg_width}" d="${stand_height}"
    />
</inertial>

<visual name="stand_leg_${number}_visual_2">
    <pose>
        ${stand_radius*cos(yaw)}
        ${stand_radius*sin(yaw)}
        ${-stand_height + stand_base_height/2}
        0 0 ${yaw}
    </pose>
    <geometry>
        <cylinder>
            <length>${stand_base_height}</length>
            <radius>${stand_base_radius}</radius>
        </cylinder>
    </geometry>
</visual>
<collision name="stand_leg_${number}_collision_2">
    <pose>
        ${stand_radius*cos(yaw)}
        ${stand_radius*sin(yaw)}
        ${-stand_height + stand_base_height/2}
        0 0 ${yaw}
    </pose>
    <geometry>
        <cylinder>
            <length>${stand_base_height}</length>
            <radius>${stand_base_radius}</radius>
        </cylinder>
    </geometry>
    <surface>
        <ode>
            <mu>10</mu>
            <mu2>10</mu2>
            <slip>0</slip>
            <slip2>0</slip2>
        </ode>
    </surface>
</collision>
<inertial>
    <pose>
        ${stand_radius*cos(yaw)} ${stand_radius*sin(yaw)} ${-stand_height+stand_base_height/2}
        0 0 {yaw}
    </pose>
    <mass>${base_mass}</mass>
    <xacro:cylinder_inertia_sdf
        mass="${stand_base_mass}" radius="${stand_base_radius}" length="${stand_base_height}"
    />
</inertial>

<visual name="stand_top_${number}_visual_3">
    <pose>
        ${0.5*(stand_radius+base_radius)*cos(yaw)}
        ${0.5*(stand_radius+base_radius)*sin(yaw)}
        0
        0 0 ${yaw}
    </pose>
    <geometry><box><size>
        ${stand_radius - base_radius}
        ${stand_leg_width}
        ${stand_leg_depth}
    </size></box></geometry>
</visual>
<collision name="stand_leg_base_${number}_collision_3">
    <pose>
        ${0.5*(stand_radius+base_radius)*cos(yaw)}
        ${0.5*(stand_radius+base_radius)*sin(yaw)}
        0
        0 0 ${yaw}
    </pose>
    <geometry><box><size>
        ${stand_radius - base_radius}
        ${stand_leg_width}
        ${stand_leg_depth}
    </size></box></geometry>
</collision>
<inertial>
    <pose>
        ${0.5*(stand_radius+base_radius)*cos(yaw)}
        ${0.5*(stand_radius+base_radius)*sin(yaw)}
        0
        0 0 ${yaw}
    </pose>
    <xacro:box_inertia_sdf
        mass="${stand_horizontal_mass}"
        w="${stand_radius - base_radius}"
        h="${stand_leg_width}"
        d="${stand_leg_depth}"
    />
</inertial>

</xacro:macro>

<link name="base">
<pose> 0 0 ${stand_height} 0 0 0</pose>

<visual name="base_visual">
    <geometry>
        <cylinder>
            <length>${base_depth}</length>
            <radius>${base_radius}</radius>
        </cylinder>
    </geometry>
</visual>

<collision name="base_collision">
    <geometry>
        <cylinder>
            <length>${base_depth}</length>
            <radius>${base_radius}</radius>
        </cylinder>
    </geometry>
</collision>

<inertial>
    <mass>${base_mass}</mass>
    <xacro:cylinder_inertia_sdf
        mass="${base_mass}"
        radius="${base_radius}"
        length="${base_depth}"
    />
</inertial>

<!--
<xacro:stand_part number="1" yaw="${pi/3}"/>
<xacro:stand_part number="2" yaw="${pi}"/>
<xacro:stand_part number="3" yaw="${-pi/3}"/>
-->

</link>

</sdf>
