<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">

<xacro:macro name="ee_attachment" params="number yaw">
<visual name="ee_attachment_${number}_visual">
    <pose>
        ${ee_radius*cos(yaw)}
        ${ee_radius*sin(yaw)}
        0
        0 ${pi/2} ${yaw + pi/2}
    </pose>
    <geometry>
        <cylinder>
            <length>${lower_width}</length>
            <radius>${ee_depth/2}</radius>
        </cylinder>
    </geometry>
</visual>
<collision name="ee_attachment_${number}_collision">
    <pose>
        ${ee_radius*cos(yaw)}
        ${ee_radius*sin(yaw)}
        0
        0 ${pi/2} ${yaw + pi/2}
    </pose>
    <geometry>
        <cylinder>
            <length>${lower_width}</length>
            <radius>${ee_depth/2}</radius>
        </cylinder>
    </geometry>
</collision>
</xacro:macro>

<link name="ee">
<pose> 0 0 ${ee_height} 0 0 0</pose>

<visual name="ee_visual">
    <pose>0 0 0 0 0 0</pose>
    <geometry>
        <cylinder>
            <length>${ee_depth}</length>
            <radius>${ee_radius}</radius>
        </cylinder>
    </geometry>
</visual>

<collision name="ee_collision">
    <pose>0 0 0 0 0 0</pose>
    <geometry>
        <cylinder>
            <length>${ee_depth}</length>
            <radius>${ee_radius}</radius>
        </cylinder>
    </geometry>
</collision>

<xacro:ee_attachment number="1" yaw="0"/>
<xacro:ee_attachment number="2" yaw="${2*pi/3}"/>
<xacro:ee_attachment number="3" yaw="${-2*pi/3}"/>

<inertial>
    <mass>${ee_mass}</mass>
    <xacro:cylinder_inertia_sdf
        mass="${ee_mass}"
        radius="${ee_radius}"
        length="${ee_depth}"
    />
</inertial>

</link>

</robot>
