<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">

<xacro:macro name="end_effector_attachment" params="number yaw">
<visual name="end_effector_attachment_${number}_visual">
    <pose>
        ${end_effector_radius*cos(yaw)}
        ${end_effector_radius*sin(yaw)}
        0
        0 ${pi/2} ${yaw + pi/2}
    </pose>
    <geometry>
        <cylinder>
            <length>${lower_width}</length>
            <radius>${end_effector_depth/2}</radius>
        </cylinder>
    </geometry>
</visual>
<collision name="end_effector_attachment_${number}_collision">
    <pose>
        ${end_effector_radius*cos(yaw)}
        ${end_effector_radius*sin(yaw)}
        0
        0 ${pi/2} ${yaw + pi/2}
    </pose>
    <geometry>
        <cylinder>
            <length>${lower_width}</length>
            <radius>${end_effector_depth/2}</radius>
        </cylinder>
    </geometry>
</collision>
</xacro:macro>

<link name="end_effector">
<pose> 0 0 ${end_effector_height} 0 0 0</pose>

<visual name="end_effector_visual">
    <pose>0 0 0 0 0 0</pose>
    <geometry>
        <cylinder>
            <length>${end_effector_depth}</length>
            <radius>${end_effector_radius}</radius>
        </cylinder>
    </geometry>
</visual>

<collision name="end_effector_collision">
    <pose>0 0 0 0 0 0</pose>
    <geometry>
        <cylinder>
            <length>${end_effector_depth}</length>
            <radius>${end_effector_radius}</radius>
        </cylinder>
    </geometry>
</collision>

<xacro:end_effector_attachment number="1" yaw="0"/>
<xacro:end_effector_attachment number="2" yaw="${2*pi/3}"/>
<xacro:end_effector_attachment number="3" yaw="${-2*pi/3}"/>

<inertial>
    <mass>${end_effector_mass}</mass>
    <xacro:cylinder_inertia_sdf
        mass="${end_effector_mass}"
        radius="${end_effector_radius}"
        length="${end_effector_depth}"
    />
</inertial>

</link>

</robot>
