theta_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - theta_1
        - theta_2
        - theta_3

gripper_controller:
    type: position_controllers/JointGrouPositionController
    joints:
        - gripper

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
