gazebo_ros_control:
    pid_gains:
        theta_1: {p: 300, i: 0, d: 0.5}
        theta_2: {p: 300, i: 0, d: 0.5}
        theta_3: {p: 300, i: 0, d: 0.5}
        theta_4: {p: 1, i: 0, d: 0}
        gripper: {p: 1, i: 0, d: 0}
