theta_1_controller:
    type: position_controllers/JointPositionController
    joint: theta_1

theta_2_controller:
    type: position_controllers/JointPositionController
    joint: theta_2

theta_3_controller:
    type: position_controllers/JointPositionController
    joint: theta_3

theta_4_controller:
    type: position_controllers/JointPositionController
    joint: theta_4

theta_5_controller:
    type: position_controllers/JointPositionController
    joint: theta_5

theta_6_controller:
    type: position_controllers/JointPositionController
    joint: theta_6

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
