# The gazebo_ros_control plugin isn't working for some reason,
# so omit the control gains so it doesn't simulate dynamics

# gazebo_ros_control:
#     pid_gains:
#         theta_1: {p: 1, i: 0.1, d: 0.01}
#         theta_2: {p: 1, i: 0.1, d: 0.01}
#         theta_3: {p: 1, i: 0.1, d: 0.01}
#         theta_4: {p: 1, i: 0.1, d: 0.01}
#         theta_5: {p: 0, i: 0, d: 0}
#         theta_6: {p: 0, i: 0, d: 0}
