# Omitting dynamics - difficult to get it right

# gazebo_ros_control:
#     pid_gains:
#         theta_1: {p: 20, i: 0, d: 1}
#         theta_2: {p: 80, i: 0, d: 5}
#         theta_3: {p: 30, i: 0, d: 1}
#         theta_4: {p: 20, i: 0, d: 0.1}
#         theta_5: {p: 5, i: 0, d: 0.5}
#         theta_6: {p: 1, i: 0, d: 0.1}
