theta_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - theta_1
        - theta_1
        - theta_3
        - theta_4
        - theta_5
        - theta_6

gripper_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - gripper

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
