<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">

<xacro:macro name="joints_ee" params="number yaw">

<joint name="lower_${number}_L_ball_bot" type="ball">
    <pose>
        ${ee_radius*cos(yaw) - (lower_width/2)*sin(yaw)}
        ${ee_radius*sin(yaw) + (lower_width/2)*cos(yaw)}
        0
        0 0 ${yaw}
    </pose>
    <parent>lower_${number}_L_link</parent>
    <child>ee</child>
</joint>

<joint name="lower_${number}_R_ball_bot" type="ball">
    <pose>
        ${ee_radius*cos(yaw) + (lower_width/2)*sin(yaw)}
        ${ee_radius*sin(yaw) - (lower_width/2)*cos(yaw)}
        0
        0 0 ${yaw}
    </pose>
    <parent>lower_${number}_R_link</parent>
    <child>ee</child>
</joint>

</xacro:macro>

<xacro:joints_ee number="1" yaw="0"/>
<xacro:joints_ee number="2" yaw="${2*pi/3}"/>
<xacro:joints_ee number="3" yaw="${-2*pi/3}"/>

</robot>
